<div class="leo-page"><div class="leo-container">
    <header class="leo-header"><div><h1 class="leo-title">Clientes</h1><p class="leo-subtitle">Datos fiscales y de contacto de quienes compran en LEO AutoParts.</p></div>@if(auth()->user()->role_id !== 3)<button wire:click="create" class="leo-button-primary">+ Nuevo cliente</button>@endif</header>
    <section class="leo-card p-4"><div class="grid gap-3 sm:grid-cols-[minmax(0,1fr)_14rem]"><div><x-input-label>Buscar cliente</x-input-label><x-text-input wire:model.live.debounce.300ms="search" class="leo-field" placeholder="Nombre, DNI/RUC, correo o teléfono..." /></div><div><x-input-label>Tipo</x-input-label><x-select wire:model.live="typeFilter" class="leo-field"><option value="all">Todos los tipos</option>@foreach($customer_types as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</x-select></div></div></section>
    <section class="leo-table-wrap hidden md:block"><table class="leo-table"><thead><tr><th>Cliente</th><th>Identificación</th><th>Contacto</th><th>Ubicación</th><th>Tipo</th>@if(auth()->user()->role_id !== 3)<th class="text-center">Acciones</th>@endif</tr></thead><tbody>
        @forelse($customers as $item)<tr><td><p class="font-bold text-slate-950">{{ $item->name }}</p><p class="text-xs text-slate-500">{{ $item->email }}</p></td><td>{{ $item->dni_ruc }}</td><td><p>{{ $item->phone }}</p><p class="text-xs text-slate-500">{{ $item->email }}</p></td><td><p>{{ $item->city }}</p><p class="max-w-xs truncate text-xs text-slate-500">{{ $item->address }}</p></td><td><span class="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{{ $item->customerType?->name ?? 'Sin tipo' }}</span></td>@if(auth()->user()->role_id !== 3)<td><div class="flex justify-center gap-2"><button wire:click="update({{ $item->id }})" class="rounded-lg bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700">Editar</button><button wire:click="$dispatch('confirmDeleteCustomer',{id:{{ $item->id }}})" class="rounded-lg bg-red-50 px-3 py-1.5 text-xs font-bold text-red-700">Eliminar</button></div></td>@endif</tr>
        @empty<tr><td colspan="6" class="py-16 text-center text-slate-500">No hay clientes que coincidan con la búsqueda.</td></tr>@endforelse
    </tbody></table></section>
    <section class="grid gap-3 md:hidden">@forelse($customers as $item)<article class="leo-card p-4"><div class="flex items-start justify-between gap-3"><div><p class="font-bold text-slate-950">{{ $item->name }}</p><p class="text-xs text-slate-500">{{ $item->dni_ruc }}</p></div><span class="rounded-full bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">{{ $item->customerType?->name }}</span></div><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-xs text-slate-400">Teléfono</dt><dd>{{ $item->phone }}</dd></div><div><dt class="text-xs text-slate-400">Ciudad</dt><dd>{{ $item->city }}</dd></div><div class="col-span-2"><dt class="text-xs text-slate-400">Correo</dt><dd class="break-all">{{ $item->email }}</dd></div></dl>@if(auth()->user()->role_id !== 3)<div class="mt-4 flex gap-2 border-t border-slate-100 pt-3"><button wire:click="update({{ $item->id }})" class="leo-button flex-1 bg-amber-50 text-amber-700">Editar</button><button wire:click="$dispatch('confirmDeleteCustomer',{id:{{ $item->id }}})" class="leo-button flex-1 bg-red-50 text-red-700">Eliminar</button></div>@endif</article>@empty<p class="leo-card py-12 text-center text-slate-500">No hay clientes.</p>@endforelse</section>
    <div>{{ $customers->links('custom-tailwind') }}</div>
</div>
<form wire:submit="save"><x-dialog-modal name="modal-form-customer" maxWidth="2xl"><x-slot name="title"><div><h2 class="text-xl font-bold">{{ $isEditing ? 'Editar cliente' : 'Nuevo cliente' }}</h2><p class="text-sm text-slate-500">Información fiscal, de contacto y ubicación.</p></div></x-slot><x-slot name="content"><div class="grid gap-4 sm:grid-cols-2"><div><x-input-label>DNI / RUC</x-input-label><x-text-input wire:model="customer.dni_ruc" class="leo-field" />@error('customer.dni_ruc')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><div><x-input-label>Nombre</x-input-label><x-text-input wire:model="customer.name" class="leo-field" />@error('customer.name')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><div><x-input-label>Correo electrónico</x-input-label><x-text-input type="email" wire:model="customer.email" class="leo-field" />@error('customer.email')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><div><x-input-label>Teléfono</x-input-label><x-text-input wire:model="customer.phone" class="leo-field" />@error('customer.phone')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><div class="sm:col-span-2"><x-input-label>Dirección</x-input-label><x-text-input wire:model="customer.address" class="leo-field" />@error('customer.address')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><div><x-input-label>Ciudad</x-input-label><x-select wire:model="customer.city" class="leo-field">@foreach($cities as $city)<option>{{ $city }}</option>@endforeach</x-select></div><div><x-input-label>Tipo de cliente</x-input-label><x-select wire:model="customer.customer_type_id" class="leo-field">@foreach($customer_types as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</x-select></div></div></x-slot><x-slot name="footer"><div class="flex gap-2"><button type="button" wire:click="$dispatch('close-modal','modal-form-customer')" class="leo-button">Cancelar</button><button type="submit" class="leo-button-primary">Guardar cliente</button></div></x-slot></x-dialog-modal></form>
@script<script>$wire.on('confirmDeleteCustomer',({id})=>{Swal.fire({title:'¿Eliminar cliente?',text:'El registro dejará de aparecer en las operaciones nuevas.',icon:'warning',showCancelButton:true,confirmButtonText:'Sí, eliminar',cancelButtonText:'Cancelar',confirmButtonColor:'#dc2626'}).then(r=>{if(r.isConfirmed)$wire.destroy(id)})});$wire.on('customerSaved',()=>Swal.fire({title:'Cliente guardado',icon:'success',timer:1400,showConfirmButton:false}));$wire.on('customerDeleted',()=>Swal.fire({title:'Cliente eliminado',icon:'success',timer:1400,showConfirmButton:false}));</script>@endscript
</div>
