<div class="leo-page"><div class="leo-container">
    <header class="leo-header"><div><h1 class="leo-title">Caja</h1><p class="leo-subtitle">Apertura, movimientos, arqueo y cierre diario.</p></div>@if($current)<span class="rounded-full bg-emerald-100 px-4 py-2 text-sm font-bold text-emerald-700">● Caja abierta</span>@else<span class="rounded-full bg-slate-200 px-4 py-2 text-sm font-bold text-slate-600">Caja cerrada</span>@endif</header>
    @error('cash')<div class="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{{ $message }}</div>@enderror

    @if(!$current)
        <section class="leo-card mx-auto max-w-xl p-6 sm:p-8"><div class="text-center"><div class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-100 text-2xl font-black text-blue-600">$</div><h2 class="mt-4 text-xl font-bold text-slate-950">Abrir caja</h2><p class="mt-1 text-sm text-slate-500">Registre el fondo disponible al iniciar la jornada.</p></div>
            <form wire:submit="openCash" class="mt-6 space-y-4"><div><x-input-label>Fondo inicial</x-input-label><x-text-input type="number" min="0" step="0.01" wire:model="openingAmount" class="leo-field text-lg font-bold" />@error('openingAmount')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</div><div><x-input-label>Observaciones</x-input-label><x-textarea wire:model="openingNotes" class="leo-field min-h-24" /></div><x-primary-button class="leo-button-primary w-full">Abrir caja</x-primary-button></form>
        </section>
    @else
        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <article class="leo-card p-5"><p class="text-sm font-semibold text-slate-500">Fondo inicial</p><p class="mt-2 text-2xl font-black">$ {{ number_format($current->opening_amount,2) }}</p></article>
            <article class="leo-card border-l-4 border-l-emerald-500 p-5"><p class="text-sm font-semibold text-slate-500">Entradas</p><p class="mt-2 text-2xl font-black text-emerald-600">$ {{ number_format($income,2) }}</p></article>
            <article class="leo-card border-l-4 border-l-red-500 p-5"><p class="text-sm font-semibold text-slate-500">Salidas</p><p class="mt-2 text-2xl font-black text-red-600">$ {{ number_format($expenses,2) }}</p></article>
            <article class="leo-card border-l-4 border-l-blue-500 p-5"><p class="text-sm font-semibold text-slate-500">Efectivo esperado</p><p class="mt-2 text-2xl font-black text-blue-600">$ {{ number_format($expected,2) }}</p></article>
        </section>
        <section class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_24rem]">
            <div class="leo-card overflow-hidden"><div class="leo-card-header"><h2 class="font-bold text-slate-950">Movimientos de la sesión</h2><p class="text-sm text-slate-500">Abierta por {{ $current->openedBy?->name }} el {{ $current->opened_at->format('d/m/Y H:i') }}</p></div>
                <form wire:submit="addMovement" class="grid gap-3 bg-slate-50 p-4 sm:grid-cols-[9rem_10rem_minmax(0,1fr)_auto] sm:items-end"><div><x-input-label>Tipo</x-input-label><x-select wire:model="movementType" class="leo-field"><option value="income">Entrada</option><option value="expense">Salida</option></x-select></div><div><x-input-label>Importe</x-input-label><x-text-input type="number" min="0.01" step="0.01" wire:model="movementAmount" class="leo-field" /></div><div><x-input-label>Descripción</x-input-label><x-text-input wire:model="movementDescription" class="leo-field" placeholder="Concepto del movimiento" /></div><x-primary-button class="leo-button-dark">Registrar</x-primary-button></form>
                @error('movement')<div class="p-3 text-sm text-red-600">{{ $message }}</div>@enderror
                <div class="overflow-x-auto"><table class="leo-table"><thead><tr><th>Hora</th><th>Descripción</th><th>Responsable</th><th class="text-right">Importe</th></tr></thead><tbody>@forelse($current->movements->sortByDesc('occurred_at') as $movement)<tr><td>{{ $movement->occurred_at->format('H:i') }}</td><td>{{ $movement->description }}</td><td>{{ $movement->user?->name ?? 'Sistema' }}</td><td class="text-right font-bold {{ $movement->type==='income'?'text-emerald-600':'text-red-600' }}">{{ $movement->type==='income'?'+':'-' }} $ {{ number_format($movement->amount,2) }}</td></tr>@empty<tr><td colspan="4" class="py-12 text-center text-slate-500">No hay movimientos manuales.</td></tr>@endforelse</tbody></table></div>
            </div>
            <form wire:submit="closeCash" class="leo-card h-fit border-amber-200 p-5"><h2 class="mt-1 text-lg font-bold text-slate-950">Cerrar caja</h2><p class="mt-1 text-sm text-slate-500">Cuente el efectivo disponible físicamente.</p><div class="mt-4"><x-input-label>Efectivo contado</x-input-label><x-text-input type="number" min="0" step="0.01" wire:model="closingAmount" class="leo-field text-lg font-bold" /></div><div class="mt-3"><x-input-label>Observaciones</x-input-label><x-textarea wire:model="closingNotes" class="leo-field min-h-20" /></div><x-primary-button class="leo-button mt-4 w-full bg-amber-500 text-slate-950 hover:bg-amber-400">Cerrar y calcular diferencia</x-primary-button></form>
        </section>
    @endif

    <section class="leo-table-wrap"><div class="leo-card-header"><h2 class="font-bold text-slate-950">Historial de cajas</h2></div><table class="leo-table"><thead><tr><th>Apertura</th><th>Responsable</th><th class="text-right">Inicial</th><th class="text-right">Esperado</th><th class="text-right">Contado</th><th class="text-right">Diferencia</th><th>Estado</th></tr></thead><tbody>@forelse($sessions as $session)<tr><td>{{ $session->opened_at->format('d/m/Y H:i') }}</td><td>{{ $session->openedBy?->name }}</td><td class="text-right">$ {{ number_format($session->opening_amount,2) }}</td><td class="text-right">{{ $session->expected_amount!==null?'$ '.number_format($session->expected_amount,2):'—' }}</td><td class="text-right">{{ $session->closing_amount!==null?'$ '.number_format($session->closing_amount,2):'—' }}</td><td class="text-right font-bold {{ ($session->difference??0)<0?'text-red-600':'text-emerald-600' }}">{{ $session->difference!==null?'$ '.number_format($session->difference,2):'—' }}</td><td><span class="rounded-full px-2 py-1 text-xs font-bold {{ $session->status==='open'?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-600' }}">{{ $session->status==='open'?'Abierta':'Cerrada' }}</span></td></tr>@empty<tr><td colspan="7" class="py-12 text-center text-slate-500">No hay sesiones de caja registradas.</td></tr>@endforelse</tbody></table><div class="p-3">{{ $sessions->links('custom-tailwind') }}</div></section>
    @script<script>$wire.on('cashUpdated', ({message}) => Swal.fire({title:message,icon:'success',confirmButtonColor:'#2563eb'}));</script>@endscript
</div></div>
