<div class="leo-page"><div class="leo-container">
<header class="leo-header"><div><h1 class="leo-title">Proveedores</h1><p class="leo-subtitle">Directorio de empresas y contactos que abastecen el inventario.</p></div><button wire:click="create" class="leo-button-primary">+ Nuevo proveedor</button></header>
<section class="leo-card p-4"><x-input-label>Buscar proveedor</x-input-label><x-text-input wire:model.live.debounce.300ms="search" class="leo-field" placeholder="Nombre, contacto o teléfono..." /></section>
<section class="leo-table-wrap hidden md:block"><table class="leo-table"><thead><tr><th>Proveedor</th><th>Persona de contacto</th><th>Teléfono</th><th>Dirección</th><th class="text-center">Acciones</th></tr></thead><tbody>@forelse($suppliers as $item)<tr><td class="font-bold text-slate-950">{{ $item->name }}</td><td>{{ $item->contact }}</td><td>{{ $item->phone }}</td><td>{{ $item->address }}</td><td><div class="flex justify-center gap-2"><button wire:click="update({{ $item->id }})" class="rounded-lg bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700">Editar</button><button wire:click="$dispatch('confirmDeleteSupplier',{id:{{ $item->id }}})" class="rounded-lg bg-red-50 px-3 py-1.5 text-xs font-bold text-red-700">Eliminar</button></div></td></tr>@empty<tr><td colspan="5" class="py-16 text-center text-slate-500">No hay proveedores que coincidan con la búsqueda.</td></tr>@endforelse</tbody></table></section>
<section class="grid gap-3 md:hidden">@forelse($suppliers as $item)<article class="leo-card p-4"><p class="font-bold text-slate-950">{{ $item->name }}</p><p class="text-sm text-blue-600">{{ $item->contact }}</p><dl class="mt-4 space-y-2 text-sm"><div><dt class="text-xs text-slate-400">Teléfono</dt><dd>{{ $item->phone }}</dd></div><div><dt class="text-xs text-slate-400">Dirección</dt><dd>{{ $item->address }}</dd></div></dl><div class="mt-4 flex gap-2 border-t border-slate-100 pt-3"><button wire:click="update({{ $item->id }})" class="leo-button flex-1 bg-amber-50 text-amber-700">Editar</button><button wire:click="$dispatch('confirmDeleteSupplier',{id:{{ $item->id }}})" class="leo-button flex-1 bg-red-50 text-red-700">Eliminar</button></div></article>@empty<p class="leo-card py-12 text-center text-slate-500">No hay proveedores.</p>@endforelse</section><div>{{ $suppliers->links('custom-tailwind') }}</div>
</div>
<form wire:submit="save"><x-dialog-modal name="modal-form-supplier" maxWidth="lg"><x-slot name="title"><div><h2 class="text-xl font-bold">{{ $isEditing ? 'Editar proveedor' : 'Nuevo proveedor' }}</h2></div></x-slot><x-slot name="content"><div class="grid gap-4 sm:grid-cols-2"><div class="sm:col-span-2"><x-input-label>Nombre o razón social</x-input-label><x-text-input wire:model="supplier.name" class="leo-field" />@error('supplier.name')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><div><x-input-label>Persona de contacto</x-input-label><x-text-input wire:model="supplier.contact" class="leo-field" />@error('supplier.contact')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><div><x-input-label>Teléfono</x-input-label><x-text-input wire:model="supplier.phone" class="leo-field" />@error('supplier.phone')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><div class="sm:col-span-2"><x-input-label>Dirección</x-input-label><x-textarea wire:model="supplier.address" class="leo-field min-h-24" />@error('supplier.address')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div></div></x-slot><x-slot name="footer"><div class="flex gap-2"><button type="button" wire:click="$dispatch('close-modal','modal-form-supplier')" class="leo-button">Cancelar</button><button type="submit" class="leo-button-primary">Guardar proveedor</button></div></x-slot></x-dialog-modal></form>
@script<script>$wire.on('confirmDeleteSupplier',({id})=>{Swal.fire({title:'¿Eliminar proveedor?',text:'Se conservarán los documentos históricos relacionados.',icon:'warning',showCancelButton:true,confirmButtonText:'Sí, eliminar',cancelButtonText:'Cancelar',confirmButtonColor:'#dc2626'}).then(r=>{if(r.isConfirmed)$wire.destroy(id)})});$wire.on('supplierSaved',()=>Swal.fire({title:'Proveedor guardado',icon:'success',timer:1400,showConfirmButton:false}));$wire.on('supplierDeleted',()=>Swal.fire({title:'Proveedor eliminado',icon:'success',timer:1400,showConfirmButton:false}));</script>@endscript
</div>
