@php($isCash = mb_strtolower($paymentMethods->firstWhere('id', (int)$paymentMethod)?->name ?? '') === 'efectivo')
<div class="leo-page"><div class="leo-container">
    <header class="leo-header"><div><h1 class="leo-title">Nueva factura</h1><p class="leo-subtitle">Registre salidas, cobros y comprobantes de clientes.</p></div><div class="flex flex-wrap items-center gap-2"><button wire:click="clearInvoice" class="leo-button text-red-600 hover:bg-red-50">Limpiar factura</button><div class="rounded-xl bg-slate-950 px-4 py-2 text-right text-white shadow-sm dark:bg-blue-600"><span class="block text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-blue-100">Total actual</span><span class="text-xl font-black">$ {{ number_format($totalFinal,2) }}</span></div></div></header>
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif

    <section class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]">
        <div class="space-y-5">
            <article class="leo-card overflow-hidden">
                <div class="leo-card-header"><h2 class="font-bold text-slate-950">Productos disponibles</h2><p class="text-sm text-slate-500">Busque y seleccione una pieza para agregarla.</p></div>
                <div class="grid gap-3 bg-slate-50 p-4 sm:grid-cols-[10rem_minmax(0,1fr)]"><x-select wire:model.live="searchMode" class="leo-field">@foreach($fields as $field)<option>{{ $field }}</option>@endforeach</x-select><x-text-input wire:model.live.debounce.300ms="searching" class="leo-field" placeholder="Buscar producto..." /></div>
                <div class="max-h-80 overflow-auto"><table class="leo-table"><thead><tr><th>Producto</th><th>Proveedor</th><th class="text-right">Stock</th><th class="text-right">Precio</th><th class="text-center">Seleccionar</th></tr></thead><tbody>@forelse($products as $item)<tr><td><div class="flex min-w-56 items-center gap-3"><div class="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl border border-slate-200 bg-white p-1"><img src="{{ $item->image_path && Storage::disk('public')->exists($item->image_path) ? asset('storage/'.$item->image_path) : asset('storage/productImages/_default.jpg') }}" alt="{{ $item->name }}" loading="lazy" class="h-full w-full object-contain" /></div><div><p class="font-semibold text-slate-900">{{ $item->name }}</p><p class="text-xs text-slate-500">{{ $item->code }} · {{ $item->brand }} {{ $item->model }}</p></div></div></td><td>{{ $item->supplier?->name ?? '—' }}</td><td class="text-right"><span class="rounded-full px-2 py-1 text-xs font-bold {{ $item->stock > 0 ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700' }}">{{ $item->stock }}</span></td><td class="text-right font-bold">$ {{ number_format($item->price,2) }}</td><td class="text-center"><button wire:click="rowSelect({{ $item->id }})" class="rounded-lg bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700 hover:bg-blue-100">Elegir</button></td></tr>@empty<tr><td colspan="5" class="py-12 text-center text-slate-500">No se encontraron productos.</td></tr>@endforelse</tbody></table></div>
                @if($selectedProduct)<div class="flex flex-col gap-4 border-t border-slate-200 bg-blue-50/50 p-4 sm:flex-row sm:items-center"><div class="flex min-w-0 flex-1 items-center gap-4"><div class="flex h-20 w-24 shrink-0 items-center justify-center overflow-hidden rounded-xl border border-slate-200 bg-white p-2 shadow-sm"><img src="{{ $selectedProduct->image_path && Storage::disk('public')->exists($selectedProduct->image_path) ? asset('storage/'.$selectedProduct->image_path) : asset('storage/productImages/_default.jpg') }}" alt="Vista previa de {{ $selectedProduct->name }}" class="h-full w-full object-contain" /></div><div class="min-w-0"><p class="font-bold text-slate-950">{{ $selectedProduct->name }}</p><p class="text-sm text-slate-500">{{ $selectedProduct->code }} · {{ $selectedProduct->brand }}</p><p class="mt-1 text-sm font-semibold text-blue-700">Disponible: {{ $selectedProduct->stock }} · $ {{ number_format($selectedProduct->price,2) }}</p></div></div><div class="flex items-end gap-2"><div><x-input-label>Cantidad</x-input-label><x-text-input type="number" min="1" wire:model="productCount" class="leo-field w-24" /></div><button wire:click="addToInvoice({{ $selectedProduct->id }})" class="leo-button-primary">Agregar</button></div></div>@endif
            </article>

            <article class="leo-table-wrap"><div class="leo-card-header"><h2 class="font-bold text-slate-950">Detalle de factura</h2></div><table class="leo-table"><thead><tr><th>Producto</th><th class="text-right">Precio</th><th class="text-right">Cantidad</th><th class="text-right">Subtotal</th><th></th></tr></thead><tbody>@forelse($invoiceTable as $item)<tr><td><div class="flex min-w-48 items-center gap-3"><div class="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-lg border border-slate-200 bg-white p-1"><img src="{{ !empty($item['image_path']) && Storage::disk('public')->exists($item['image_path']) ? asset('storage/'.$item['image_path']) : asset('storage/productImages/_default.jpg') }}" alt="" class="h-full w-full object-contain" /></div><div><p class="font-semibold text-slate-900">{{ $item['name'] }}</p><p class="text-xs text-slate-500">{{ $item['code'] }}</p></div></div></td><td class="text-right">$ {{ number_format($item['price'],2) }}</td><td class="text-right">{{ $item['quantity'] }}</td><td class="text-right font-bold">$ {{ number_format($item['subtotal'],2) }}</td><td class="text-right"><button wire:click="removeFromInvoice({{ $item['id'] }})" class="text-xs font-bold text-red-600">Eliminar</button></td></tr>@empty<tr><td colspan="5" class="py-12 text-center text-slate-500">La factura todavía no contiene productos.</td></tr>@endforelse</tbody></table></article>
        </div>

        <aside class="h-fit space-y-4 xl:sticky xl:top-20">
            <article class="leo-card overflow-hidden"><div class="leo-card-header sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-bold text-slate-950">Cliente</h2><p class="text-sm text-slate-500">Datos del comprobante</p></div><button wire:click="openCustomerSelection" class="leo-button-dark">{{ $cId ? 'Cambiar' : 'Buscar' }}</button></div>@if($cId)<div class="space-y-3 p-4"><div><p class="text-xs text-slate-500">Nombre</p><p class="font-bold text-slate-950">{{ $cName }}</p></div><div class="grid grid-cols-2 gap-3"><div><p class="text-xs text-slate-500">DNI / RUC</p><p class="text-sm font-semibold">{{ $cDniRuc }}</p></div><div><p class="text-xs text-slate-500">Teléfono</p><p class="text-sm font-semibold">{{ $cPhone ?: '—' }}</p></div></div><div><p class="text-xs text-slate-500">Correo</p><p class="truncate text-sm">{{ $cEmail ?: '—' }}</p></div></div>@else<div class="p-5 text-center text-sm text-slate-500">Seleccione el cliente de esta venta.</div>@endif</article>
            <article class="leo-card p-5"><div class="flex items-end justify-between border-b border-slate-200 pb-4 dark:border-slate-800"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-slate-500">Total a cobrar</p><p class="mt-1 text-3xl font-black text-slate-950">$ {{ number_format($totalFinal,2) }}</p></div></div><div class="pt-4"><p class="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">Método de pago</p><div class="grid gap-2">@foreach($paymentMethods as $method)<label class="flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-slate-700 transition dark:text-slate-200 {{ (int)$paymentMethod === $method->id ? 'border-blue-500 bg-blue-50 ring-1 ring-blue-500/20 dark:bg-blue-500/15' : 'border-slate-200 bg-white hover:border-slate-400 dark:border-slate-700 dark:bg-slate-950 dark:hover:border-slate-500' }}"><input type="radio" wire:model.live="paymentMethod" value="{{ $method->id }}" class="text-blue-600 focus:ring-blue-500" /><span class="font-semibold">{{ $method->name }}</span></label>@endforeach</div></div></article>
            @if($isCash)<article class="leo-card p-5"><div><x-input-label>Importe recibido</x-input-label><x-text-input type="number" min="0" step="0.01" wire:model.live="amount" class="leo-field text-lg font-bold" /></div><div class="mt-4 flex items-center justify-between rounded-xl bg-slate-100 p-4"><span class="text-sm font-semibold text-slate-500">Cambio</span><span class="text-xl font-black text-slate-950">$ {{ number_format($change,2) }}</span></div></article>@endif
            <button wire:click="saveInvoice" wire:loading.attr="disabled" class="leo-button-success w-full py-3" @disabled(count($invoiceTable)===0 || !$cId || ($isCash && ((float)$amount < (float)$totalFinal)))>Procesar venta</button>
            <p class="text-center text-xs leading-relaxed text-slate-500">Los precios, el total y el stock serán verificados nuevamente antes de guardar.</p>
        </aside>
    </section>

    <x-full-dialog-modal name="modal-list-customers" fullScreen="true"><x-slot name="title"><div><h2 class="text-xl font-bold text-slate-950">Seleccionar cliente</h2></div></x-slot><x-slot name="content"><div class="leo-table-wrap"><table class="leo-table"><thead><tr><th>Documento</th><th>Nombre</th><th>Contacto</th><th>Ciudad</th><th></th></tr></thead><tbody>@foreach($customers as $customer)<tr><td>{{ $customer->dni_ruc }}</td><td class="font-semibold text-slate-900">{{ $customer->name }}</td><td>{{ $customer->phone }}<p class="text-xs text-slate-500">{{ $customer->email }}</p></td><td>{{ $customer->city }}</td><td class="text-right"><button wire:click="selectCustomer({{ $customer->id }})" class="leo-button-primary">Seleccionar</button></td></tr>@endforeach</tbody></table></div></x-slot><x-slot name="footer"><button wire:click="$dispatch('close-modal','modal-list-customers')" class="leo-button-dark">Cerrar</button></x-slot></x-full-dialog-modal>
    @script<script>
        $wire.on('noStock',()=>Swal.fire({title:'Stock insuficiente',icon:'error',confirmButtonColor:'#2563eb'}));
        $wire.on('saleError',(message)=>Swal.fire({title:'No fue posible guardar',text:message,icon:'error',confirmButtonColor:'#2563eb'}));
        $wire.on('downloadInvoice',(url)=>Swal.fire({title:'Factura generada',text:'¿Desea abrir el comprobante?',icon:'success',showCancelButton:true,confirmButtonText:'Abrir factura',cancelButtonText:'Después',confirmButtonColor:'#2563eb'}).then(r=>{if(r.isConfirmed)window.open(url,'_blank')}));
    </script>@endscript
</div></div>
